[package]
name = "docker-volume-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
tar = "0.4.40"
flate2 = "1.0.28"